- name: Copy input from head to worker
  hosts: cluster_head
  tasks:
    - name: Copy data from head to worker
      synchronize:
        src: /home/ec2-user/data/COMP0235/input_data/batch_2/*
        dest: /home/ec2-user/data/COMP0235/input
        mode: pull
      delegate_to: "{{ groups['cluster_worker'][0] }}"
    - name: Copy data from head to worker
      synchronize:
        src: /home/ec2-user/data/COMP0235/input_data/batch_3/*
        dest: /home/ec2-user/data/COMP0235/input
        mode: pull
      delegate_to: "{{ groups['cluster_worker'][1] }}"
    - name: Copy data from head to worker
      synchronize:
        src: /home/ec2-user/data/COMP0235/input_data/batch_4/*
        dest: /home/ec2-user/data/COMP0235/input
        mode: pull
      delegate_to: "{{ groups['cluster_worker'][2] }}"
    - name: Copy data from head to worker
      synchronize:
        src: /home/ec2-user/data/COMP0235/input_data/batch_5/*
        dest: /home/ec2-user/data/COMP0235/input
        mode: pull
      delegate_to: "{{ groups['cluster_worker'][3] }}"
