- name: Copy from worker to head
  hosts: cluster_head
  tasks:
    - name: Copy from worker to head
      synchronize:
        src: /home/ec2-user/data/COMP0235/output
        dest: /home/ec2-user/data/COMP0235/output
        mode: push
      delegate_to: "{{ groups['cluster_worker'][0] }}"
    - name: move file
      ansible.builtin.shell: |
        mv /home/ec2-user/data/COMP0235/output/output/* /home/ec2-user/data/COMP0235/output/
    - name: Copy from worker to head
      synchronize:
        src: /home/ec2-user/data/COMP0235/output
        dest: /home/ec2-user/data/COMP0235/output
        mode: push
      delegate_to: "{{ groups['cluster_worker'][1] }}"
    - name: move file
      ansible.builtin.shell: |
        mv /home/ec2-user/data/COMP0235/output/output/* /home/ec2-user/data/COMP0235/output/
    - name: Copy from worker to head
      synchronize:
        src: /home/ec2-user/data/COMP0235/output
        dest: /home/ec2-user/data/COMP0235/output
        mode: push
      delegate_to: "{{ groups['cluster_worker'][2] }}"
    - name: move file
      ansible.builtin.shell: |
        mv /home/ec2-user/data/COMP0235/output/output/* /home/ec2-user/data/COMP0235/output/
    - name: Copy from worker to head
      synchronize:
        src: /home/ec2-user/data/COMP0235/output
        dest: /home/ec2-user/data/COMP0235/output
        mode: push
      delegate_to: "{{ groups['cluster_worker'][3] }}"
    - name: move file
      ansible.builtin.shell: |
        mv /home/ec2-user/data/COMP0235/output/output/* /home/ec2-user/data/COMP0235/output/

