- name: install s4pred
  hosts: cluster_head
  tasks:
    - name: Create data folder
      ansible.builtin.file:
        path: data/s4pred
        state: directory
        mode: '0755'
    - name: Clone a github repository
      git:
        repo: https://github.com/psipred/s4pred.git
        dest: data/s4pred
    - name: Get weight
      ansible.builtin.shell: cd data/s4pred && wget http://bioinfadmin.cs.ucl.ac.uk/downloads/s4pred/weights.tar.gz && tar -xvzf weights.tar.gz && rm weights.tar.gz
